#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get honey/username
username="$RET"
echo "the username you entered was: $username"

db_get honey/name
name="$RET"
echo "Your full name is: $name"

db_get honey/like_debian
great="$RET"
echo "so your answer was, $great"
db_stop
